Submission of Flutter Sample for GSOC
divyanshub024/awesome-dart-pad pull request #47
Opened 2020-03-24 17:47 UTC by nuelsoft

2020-03-30 06:36 UTC, divyanshub024 requested changes
Please remove art/WhatsApp Video 2020-03-24 at 18.23.13.mp4

2020-03-30 06:36 UTC, divyanshub024 commented on README.md
> +
Please remove this extra line

2020-03-30 08:10 UTC, nuelsoft commented on README.md
> +
Done Sir. Deleted the mp4.

2020-04-04 12:00 UTC, divyanshub024 approved these changes
Thanks a lot for your contribution! 🙏

2020-04-04 12:00 UTC, merged