GSOC-2020 Playing with Flex.
divyanshub024/awesome-dart-pad pull request #59
Opened 2020-03-31 13:02 UTC by sarannng

Please go throught [How to contribute guide](https://github.com/divyanshub024/awesome-dart-pad/blob/master/Contribution.md) before creating a PR.

2020-03-31 17:02 UTC, mkiisoft requested changes

2020-03-31 17:02 UTC, mkiisoft commented on README.md
> +  - [Playing-with-Flex](https://dartpad.dev/2889325c3f7b0ad13a6950ad065f7bbe) by [Sarang Pal](https://github.com/sarannng)(31/03/2020)
remove extra space

2020-03-31 17:03 UTC, mkiisoft commented
Would be nice to have a detailed PR telling what you did, a GIF/Screenshot of your implementation, etc instead of the detail message:

"Please go throught How to contribute guide before creating a PR."

Thanks for your contribution!

2020-03-31 17:17 UTC, mkiisoft requested changes

2020-03-31 17:17 UTC, mkiisoft commented on README.md
> +  - [Playing-with-Flex](https://dartpad.dev/2889325c3f7b0ad13a6950ad065f7bbe) by [Sarang Pal](https://github.com/sarannng)(31/03/2020)
The space is for line 133

2020-04-04 12:08 UTC, divyanshub024 approved these changes
Thanks a lot for your contribution! 🙏

2020-04-04 12:08 UTC, merged