Reactive ListView with StreamController
divyanshub024/awesome-dart-pad pull request #61
Opened 2020-03-31 17:46 UTC by yurisasc

Simulated how to implement a reactive ListView by using StreamController.
Uses simple planet facts as local data that is shown to the UI periodically.

Link to Dartpad: https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b

2020-03-31 19:13 UTC, mkiisoft commented
https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b is the default gist for increment counter, please, provide your own gist/dartpad.

2020-03-31 19:14 UTC, mkiisoft requested changes

2020-03-31 19:14 UTC, mkiisoft commented on README.md
> +- [Reactive-ListView](https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b) by [Yuris Cakranegara](https://https://github.com/yurisasc)(04/01/2020)
provide your own gist/dartpad and not default one

2020-03-31 19:14 UTC, mkiisoft commented on README.md
> +  [<img src = "/art/ReactiveListView.gif" width="240">](https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b)
same for this one

2020-03-31 19:29 UTC, yurisasc commented on README.md
> +  [<img src = "/art/ReactiveListView.gif" width="240">](https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b)
Thank you, and sorry for the trouble.

2020-04-04 11:54 UTC, divyanshub024 approved these changes

2020-04-04 11:55 UTC, divyanshub024 commented
@mkiisoft Thanks a lot for reviewing the PR.

2020-04-04 11:55 UTC, merged